### PR TITLE
Update cow and mooshroom

### PR DESCRIPTION
**Pull request by Wuzzy2**
* Merge cow and mooshroom in single source file
* Fix size
* Add milk item
* Using shears on mooshroom gives 5 red mushrooms and turns it into a cow
* Change model/texture file names to obey naming conventions

### CODE REVIEW

**Comment by Vespidian** [comment]
If mooshroom is clicked with a wooden bowl it gives soup but you would need to add soup and bowl items

**Comment by Wuzzy2** [comment]
Bowl and mushroom stew items added. I think the way this mod currently handles items should be temporary and be replaced with a more generic approach later.

**Comment by maikerumine** [comment]
This branch has conflicts that must be resolved
 Use the command line to resolve conflicts before continuing.

How can I resolve?

**Comment by Wuzzy2** [comment]
Please read:
https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

**Review by maikerumine — APPROVED** [review]

**Pull request merged**
